### ISSUE TITLE
Output from fix ordern and compute rdf/ext

### ISSUE THREAD

**Issue by zhaoxiao9302** [omoultosEthTuDelft/OCTP#1]
I am confused by the output from firx ordern and compute rdf/ext.

1. For fix ordern diffusivity, if you set Nwrite=100000 and timestep=1fs, then the firsr column should be like 100000,200000,300000,400000...
But the result I got from your example is that 1000,2000,3000,...,19000,20000,20000,400000,600000,80000,...
I am quite confused about the time column output. It is not consistent.
Where did it come from?

2. For compute rdf/ext,  if you set Nwrite=1000 and Nevery for RDF in ave/time to be 100, as your script, RDF file should be output every 100000 timesteps. But I only got one frame of rdf in the output file.
It should be 10 times in the rdf output when the total step is 1000000, why it is not?

So please clarity again all the frequency setting for me again. 
Thank you.

**Comment by omoultosEthTuDelft** [comment]
1. The first column in the output file in OCTP indicates the "Sampling Frequency" in the order-n algorithm. This means that you sample system properties every this timestep.  Nwrite is the output frequency which specifies how often (every how many timesteps) you write the output data files. In the given example, the self-diffusion or onsager are sampled every 1000 timesteps, that is why it proceeds 1000-2000-3000 (note that viscosity sampling is different),  but Nwrite is 100000 so if you go to the output file you can see it 100000,200000...

2. The output gives you the time-averaged rdfs between the defined groups. Depending on the writing frequency, this updates your RDF. You don't see a time evolution. Nwrite 1000 means your RDF information is updated every 1000 timestep.  

Hope these help

**Comment by omoultosEthTuDelft** [comment]
> I am confused by the output from firx ordern and compute rdf/ext.
> 
> 1. For fix ordern diffusivity, if you set Nwrite=100000 and timestep=1fs, then the firsr column should be like 100000,200000,300000,400000...
>    But the result I got from your example is that 1000,2000,3000,...,19000,20000,20000,400000,600000,80000,...
>    I am quite confused about the time column output. It is not consistent.
>    Where did it come from?
> 2. For compute rdf/ext,  if you set Nwrite=1000 and Nevery for RDF in ave/time to be 100, as your script, RDF file should be output every 100000 timesteps. But I only got one frame of rdf in the output file.
>    It should be 10 times in the rdf output when the total step is 1000000, why it is not?
> 
> So please clarity again all the frequency setting for me again.
> Thank you.


1. The first column in the output file in OCTP indicates the "Sampling Frequency" in the order-n algorithm. This means that you sample system properties every this timestep. Nwrite is the output frequency which specifies how often (every how many timesteps) you write the output data files. In the given example, the self-diffusion or onsager are sampled every 1000 timesteps, that is why it proceeds 1000-2000-3000 (note that viscosity sampling is different), but Nwrite is 100000 so if you go to the output file you can see it 100000,200000...

2. The output gives you the time-averaged rdfs between the defined groups. Depending on the writing frequency, this updates your RDF. You don't see a time evolution. Nwrite 1000 means your RDF information is updated every 1000 timestep.

Hope these help

**Comment by zhaoxiao9302** [comment]
> > I am confused by the output from firx ordern and compute rdf/ext.
> > 
> > 1. For fix ordern diffusivity, if you set Nwrite=100000 and timestep=1fs, then the firsr column should be like 100000,200000,300000,400000...
> >    But the result I got from your example is that 1000,2000,3000,...,19000,20000,20000,400000,600000,80000,...
> >    I am quite confused about the time column output. It is not consistent.
> >    Where did it come from?
> > 2. For compute rdf/ext,  if you set Nwrite=1000 and Nevery for RDF in ave/time to be 100, as your script, RDF file should be output every 100000 timesteps. But I only got one frame of rdf in the output file.
> >    It should be 10 times in the rdf output when the total step is 1000000, why it is not?
> > 
> > So please clarity again all the frequency setting for me again.
> > Thank you.
> 
> 1. The first column in the output file in OCTP indicates the "Sampling Frequency" in the order-n algorithm. This means that you sample system properties every this timestep. Nwrite is the output frequency which specifies how often (every how many timesteps) you write the output data files. In the given example, the self-diffusion or onsager are sampled every 1000 timesteps, that is why it proceeds 1000-2000-3000 (note that viscosity sampling is different), but Nwrite is 100000 so if you go to the output file you can see it 100000,200000...
> 2. The output gives you the time-averaged rdfs between the defined groups. Depending on the writing frequency, this updates your RDF. You don't see a time evolution. Nwrite 1000 means your RDF information is updated every 1000 timestep.
> 
> Hope these help

I tested it with my own script, the fix ordern command is that

timestep 0.5
fix 1 all ordern diffusivity 1000 10000 c_0
run 1000000

And my output is like 

 500 873.57 18.3633
 1000 1470.8 26.0285
 1500 2032.47 31.8343
 2000 2582.95 37.4075
 2500 3127.99 42.9162
 3000 3669.35 48.5064
 3500 4207.07 54.1377
 4000 4743.01 59.6117
 4500 5278.56 65.1052
 5000 5812.7 70.6812
 5000 5816.1 71.5798
 10000 11113.7 127.692
 15000 16407.3 183.761
 20000 21713.9 241.304
 25000 27023.3 296.902
 30000 32339.9 351.403
 35000 37655.3 405.611
 40000 42961.3 461.248
 45000 48290 517.36
 50000 53601.2 575.069
 50000 53855.3 559.781
 100000 107142 1102.94
 150000 161427 1680.78
 200000 216180 2283.32
 250000 271161 2802.58
 300000 325758 3371.55
 350000 379099 3899.21
 400000 431091 4301.15
 450000 485445 4658.47
 500000 538181 4945.54
 500000 538181 4945.54

I do not understand why the interval of time column is increasing. Is that because you are going to correlate the log-log relation? 
Can I first get a uniform interval output of time and MSD like the output from compute msd in lammps?
And at 5000, 50000, 500000 fs, there are two outputs. What is the difference here?

Thanks for the response. I really appreciate it.

**Comment by AlperTung** [comment]
> > > I am confused by the output from firx ordern and compute rdf/ext.
> > > 
> > > 1. For fix ordern diffusivity, if you set Nwrite=100000 and timestep=1fs, then the firsr column should be like 100000,200000,300000,400000...
> > >    But the result I got from your example is that 1000,2000,3000,...,19000,20000,20000,400000,600000,80000,...
> > >    I am quite confused about the time column output. It is not consistent.
> > >    Where did it come from?
> > > 2. For compute rdf/ext,  if you set Nwrite=1000 and Nevery for RDF in ave/time to be 100, as your script, RDF file should be output every 100000 timesteps. But I only got one frame of rdf in the output file.
> > >    It should be 10 times in the rdf output when the total step is 1000000, why it is not?
> > > 
> > > So please clarity again all the frequency setting for me again.
> > > Thank you.
> > 
> > 
> > 
> > 1. The first column in the output file in OCTP indicates the "Sampling Frequency" in the order-n algorithm. This means that you sample system properties every this timestep. Nwrite is the output frequency which specifies how often (every how many timesteps) you write the output data files. In the given example, the self-diffusion or onsager are sampled every 1000 timesteps, that is why it proceeds 1000-2000-3000 (note that viscosity sampling is different), but Nwrite is 100000 so if you go to the output file you can see it 100000,200000...
> > 2. The output gives you the time-averaged rdfs between the defined groups. Depending on the writing frequency, this updates your RDF. You don't see a time evolution. Nwrite 1000 means your RDF information is updated every 1000 timestep.
> > 
> > Hope these help
> 
> I tested it with my own script, the fix ordern command is that
> 
> timestep 0.5
> fix 1 all ordern diffusivity 1000 10000 c_0
> run 1000000
> 
> And my output is like
> 
> 500 873.57 18.3633
> 1000 1470.8 26.0285
> 1500 2032.47 31.8343
> 2000 2582.95 37.4075
> 2500 3127.99 42.9162
> 3000 3669.35 48.5064
> 3500 4207.07 54.1377
> 4000 4743.01 59.6117
> 4500 5278.56 65.1052
> 5000 5812.7 70.6812
> 5000 5816.1 71.5798
> 10000 11113.7 127.692
> 15000 16407.3 183.761
> 20000 21713.9 241.304
> 25000 27023.3 296.902
> 30000 32339.9 351.403
> 35000 37655.3 405.611
> 40000 42961.3 461.248
> 45000 48290 517.36
> 50000 53601.2 575.069
> 50000 53855.3 559.781
> 100000 107142 1102.94
> 150000 161427 1680.78
> 200000 216180 2283.32
> 250000 271161 2802.58
> 300000 325758 3371.55
> 350000 379099 3899.21
> 400000 431091 4301.15
> 450000 485445 4658.47
> 500000 538181 4945.54
> 500000 538181 4945.54
> 
> I do not understand why the interval of time column is increasing. Is that because you are going to correlate the log-log relation?
> Can I first get a uniform interval output of time and MSD like the output from compute msd in lammps?
> And at 5000, 50000, 500000 fs, there are two outputs. What is the difference here?
> 
> Thanks for the response. I really appreciate it.

OCTP computes the transport properties of fluids using the Einstein relations combined with the order-n algorithm.  The algorithm samples MSDs at given sampling frequencies. In order-n, several blocks (buffers)  are created, and the buffer is updated for depending on sampling frequency. MSDs are computed from the oldest element in buffer and they are added to array to obtain time-averaged MSDs.  The oldest element of the buffer is discarded and all other elements are shifted one step to create a space for the newest system property and this procedure continue This is time evolution of MSD and you need to correlate this with log-log plot to compute the transport properties.  

In your example the buffer is of size 10, so the maximum correlation time is 9deltat. You first sample 9 times in every 500fs and reaches 5000fs. This is the last element of the buffer. Now, new block starts with this through 9 times and reaches 50000fs. Continues like this. 

Please see the Dubbeldam original paper with your order-n related questions. (https://www.tandfonline.com/doi/pdf/10.1080/08927020902818039?needAccess=true)

Hope these helps

**Comment by zhaoxiao9302** [comment]
Thank you very much. I am learning about the ordern algorithm.
